// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	message.proto
	rpc_service.proto

It has these top-level messages:
	RequestHeader
	ResponseHeader
	LogInfo
	VoteRequest
	VoteResponse
	LeaderInfo
	KeepAliveRequest
	KeepAliveResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

type RequestHeader struct {
	Term uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *RequestHeader) Reset()                    { *m = RequestHeader{} }
func (m *RequestHeader) String() string            { return proto1.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()               {}
func (*RequestHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResponseHeader struct {
	Term uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
}

func (m *ResponseHeader) Reset()                    { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string            { return proto1.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()               {}
func (*ResponseHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type LogInfo struct {
	LastLogIndex uint32 `protobuf:"varint,1,opt,name=last_log_index,json=lastLogIndex" json:"last_log_index,omitempty"`
	LastLogTerm  uint32 `protobuf:"varint,2,opt,name=last_log_term,json=lastLogTerm" json:"last_log_term,omitempty"`
}

func (m *LogInfo) Reset()                    { *m = LogInfo{} }
func (m *LogInfo) String() string            { return proto1.CompactTextString(m) }
func (*LogInfo) ProtoMessage()               {}
func (*LogInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type VoteRequest struct {
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Log    *LogInfo       `protobuf:"bytes,2,opt,name=log" json:"log,omitempty"`
}

func (m *VoteRequest) Reset()                    { *m = VoteRequest{} }
func (m *VoteRequest) String() string            { return proto1.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()               {}
func (*VoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *VoteRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *VoteRequest) GetLog() *LogInfo {
	if m != nil {
		return m.Log
	}
	return nil
}

type VoteResponse struct {
	Header      *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	VoteGranted bool            `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted" json:"vote_granted,omitempty"`
}

func (m *VoteResponse) Reset()                    { *m = VoteResponse{} }
func (m *VoteResponse) String() string            { return proto1.CompactTextString(m) }
func (*VoteResponse) ProtoMessage()               {}
func (*VoteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *VoteResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type LeaderInfo struct {
	Log         *LogInfo `protobuf:"bytes,1,opt,name=log" json:"log,omitempty"`
	CommitIndex uint32   `protobuf:"varint,2,opt,name=commit_index,json=commitIndex" json:"commit_index,omitempty"`
}

func (m *LeaderInfo) Reset()                    { *m = LeaderInfo{} }
func (m *LeaderInfo) String() string            { return proto1.CompactTextString(m) }
func (*LeaderInfo) ProtoMessage()               {}
func (*LeaderInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LeaderInfo) GetLog() *LogInfo {
	if m != nil {
		return m.Log
	}
	return nil
}

type KeepAliveRequest struct {
	Header *RequestHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Leader *LeaderInfo    `protobuf:"bytes,2,opt,name=leader" json:"leader,omitempty"`
}

func (m *KeepAliveRequest) Reset()                    { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string            { return proto1.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()               {}
func (*KeepAliveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *KeepAliveRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *KeepAliveRequest) GetLeader() *LeaderInfo {
	if m != nil {
		return m.Leader
	}
	return nil
}

type KeepAliveResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (m *KeepAliveResponse) Reset()                    { *m = KeepAliveResponse{} }
func (m *KeepAliveResponse) String() string            { return proto1.CompactTextString(m) }
func (*KeepAliveResponse) ProtoMessage()               {}
func (*KeepAliveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *KeepAliveResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto1.RegisterType((*RequestHeader)(nil), "proto.RequestHeader")
	proto1.RegisterType((*ResponseHeader)(nil), "proto.ResponseHeader")
	proto1.RegisterType((*LogInfo)(nil), "proto.LogInfo")
	proto1.RegisterType((*VoteRequest)(nil), "proto.VoteRequest")
	proto1.RegisterType((*VoteResponse)(nil), "proto.VoteResponse")
	proto1.RegisterType((*LeaderInfo)(nil), "proto.LeaderInfo")
	proto1.RegisterType((*KeepAliveRequest)(nil), "proto.KeepAliveRequest")
	proto1.RegisterType((*KeepAliveResponse)(nil), "proto.KeepAliveResponse")
}

var fileDescriptor0 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x90, 0xcf, 0x4e, 0xf3, 0x30,
	0x10, 0xc4, 0x95, 0x7c, 0x1f, 0x01, 0x36, 0x7f, 0x44, 0x2d, 0x90, 0x7a, 0x2c, 0x16, 0x07, 0x90,
	0xa0, 0x87, 0xf6, 0x09, 0xe0, 0x02, 0x88, 0x5e, 0x30, 0x88, 0x1b, 0x0a, 0x81, 0x2c, 0x21, 0x22,
	0x89, 0x43, 0x6c, 0x2a, 0x1e, 0x1f, 0x67, 0x6d, 0xa2, 0x82, 0xd4, 0x4b, 0x4f, 0xb6, 0xc6, 0xbf,
	0x1d, 0xcf, 0x0e, 0xc4, 0x35, 0x2a, 0x95, 0x15, 0x38, 0x6d, 0x3b, 0xa9, 0x25, 0xdb, 0xa2, 0x83,
	0xcf, 0x21, 0x16, 0xf8, 0xf1, 0x89, 0x4a, 0x5f, 0x61, 0x96, 0x63, 0xc7, 0x18, 0xfc, 0xd7, 0xd8,
	0xd5, 0x63, 0x6f, 0xe2, 0x1d, 0xc7, 0x82, 0xee, 0x2c, 0x01, 0xbf, 0xcc, 0xc7, 0xbe, 0x51, 0x76,
	0x85, 0xb9, 0xf1, 0x23, 0x48, 0x04, 0xaa, 0x56, 0x36, 0x0a, 0xd7, 0x4f, 0xf1, 0x3b, 0xd8, 0x5e,
	0xc8, 0xe2, 0xba, 0x79, 0x95, 0xcc, 0x0c, 0x54, 0x99, 0xd2, 0x69, 0x25, 0x8b, 0xb4, 0x6c, 0x72,
	0xfc, 0x72, 0x60, 0xd4, 0xab, 0x04, 0x19, 0x8d, 0x71, 0x88, 0x07, 0x8a, 0xdc, 0x7c, 0x82, 0x42,
	0x07, 0xdd, 0xf7, 0xa6, 0x8f, 0x10, 0x3e, 0x48, 0x8d, 0x2e, 0x33, 0x3b, 0x85, 0xe0, 0x8d, 0x12,
	0x90, 0x61, 0x38, 0xdb, 0xb7, 0xdb, 0x4d, 0x7f, 0xed, 0x24, 0x1c, 0xc3, 0x26, 0xf0, 0xcf, 0x78,
	0x93, 0x6d, 0x38, 0x4b, 0x1c, 0xea, 0x32, 0x8a, 0xfe, 0x89, 0x3f, 0x41, 0x64, 0xed, 0xed, 0x76,
	0xec, 0xec, 0x8f, 0xff, 0xc1, 0xe0, 0xbf, 0xba, 0xfe, 0xf0, 0xc1, 0x21, 0x44, 0x4b, 0x33, 0x9e,
	0x16, 0x5d, 0xd6, 0x68, 0xb4, 0x95, 0xed, 0x88, 0xb0, 0xd7, 0x2e, 0xad, 0xc4, 0x6f, 0x01, 0x16,
	0x04, 0x53, 0x31, 0x2e, 0x91, 0xb7, 0x36, 0x51, 0x6f, 0xf9, 0x22, 0xeb, 0xba, 0xd4, 0xae, 0x38,
	0xd7, 0x89, 0xd5, 0xa8, 0x37, 0xfe, 0x0e, 0x7b, 0x37, 0x88, 0xed, 0x79, 0x55, 0x2e, 0x37, 0x2c,
	0xe6, 0x04, 0x82, 0xca, 0xd2, 0xb6, 0x9b, 0xd1, 0x4f, 0x92, 0x21, 0xa9, 0x70, 0x00, 0xbf, 0x80,
	0xd1, 0xca, 0x67, 0x1b, 0xd5, 0xf4, 0x1c, 0xd0, 0xeb, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x6f,
	0x1a, 0x09, 0xca, 0x93, 0x02, 0x00, 0x00,
}
