// Code generated by protoc-gen-go.
// source: append_entries.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	append_entries.proto
	install_snapshot.proto
	request_vote.proto
	rpc_service.proto

It has these top-level messages:
	LeaderInfo
	KeepAliveRequest
	KeepAliveResponse
	AppendConfigEntryRequest
	AppendLogEntryRequest
	AppendEntryResponse
	InstallSnapshotRequest
	InstallSnapshotResponse
	VoteRequest
	VoteResponse
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LeaderInfo struct {
	Term         uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	PrevLogIndex uint32 `protobuf:"varint,2,opt,name=prev_log_index" json:"prev_log_index,omitempty"`
	PrevLogTerm  uint32 `protobuf:"varint,3,opt,name=prev_log_term" json:"prev_log_term,omitempty"`
	CommitIndex  uint32 `protobuf:"varint,4,opt,name=commit_index" json:"commit_index,omitempty"`
	LeaderId     string `protobuf:"bytes,5,opt,name=leader_id" json:"leader_id,omitempty"`
}

func (m *LeaderInfo) Reset()         { *m = LeaderInfo{} }
func (m *LeaderInfo) String() string { return proto.CompactTextString(m) }
func (*LeaderInfo) ProtoMessage()    {}

type KeepAliveRequest struct {
	LeaderInfo *LeaderInfo `protobuf:"bytes,1,opt,name=leader_info" json:"leader_info,omitempty"`
}

func (m *KeepAliveRequest) Reset()         { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string { return proto.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()    {}

func (m *KeepAliveRequest) GetLeaderInfo() *LeaderInfo {
	if m != nil {
		return m.LeaderInfo
	}
	return nil
}

type KeepAliveResponse struct {
	Term uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
}

func (m *KeepAliveResponse) Reset()         { *m = KeepAliveResponse{} }
func (m *KeepAliveResponse) String() string { return proto.CompactTextString(m) }
func (*KeepAliveResponse) ProtoMessage()    {}

type AppendConfigEntryRequest struct {
	LeaderInfo    *LeaderInfo                               `protobuf:"bytes,1,opt,name=leader_info" json:"leader_info,omitempty"`
	NodeLocations map[string]*AppendConfigEntryRequest_Node `protobuf:"bytes,2,rep,name=node_locations" json:"node_locations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AppendConfigEntryRequest) Reset()         { *m = AppendConfigEntryRequest{} }
func (m *AppendConfigEntryRequest) String() string { return proto.CompactTextString(m) }
func (*AppendConfigEntryRequest) ProtoMessage()    {}

func (m *AppendConfigEntryRequest) GetLeaderInfo() *LeaderInfo {
	if m != nil {
		return m.LeaderInfo
	}
	return nil
}

func (m *AppendConfigEntryRequest) GetNodeLocations() map[string]*AppendConfigEntryRequest_Node {
	if m != nil {
		return m.NodeLocations
	}
	return nil
}

type AppendConfigEntryRequest_Node struct {
	Host string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Id   string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *AppendConfigEntryRequest_Node) Reset()         { *m = AppendConfigEntryRequest_Node{} }
func (m *AppendConfigEntryRequest_Node) String() string { return proto.CompactTextString(m) }
func (*AppendConfigEntryRequest_Node) ProtoMessage()    {}

type AppendLogEntryRequest struct {
	LeaderInfo *LeaderInfo                       `protobuf:"bytes,1,opt,name=leader_info" json:"leader_info,omitempty"`
	Entries    []*AppendLogEntryRequest_LogEntry `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
}

func (m *AppendLogEntryRequest) Reset()         { *m = AppendLogEntryRequest{} }
func (m *AppendLogEntryRequest) String() string { return proto.CompactTextString(m) }
func (*AppendLogEntryRequest) ProtoMessage()    {}

func (m *AppendLogEntryRequest) GetLeaderInfo() *LeaderInfo {
	if m != nil {
		return m.LeaderInfo
	}
	return nil
}

func (m *AppendLogEntryRequest) GetEntries() []*AppendLogEntryRequest_LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type AppendLogEntryRequest_LogEntry struct {
	Cmd   string `protobuf:"bytes,1,opt,name=cmd" json:"cmd,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *AppendLogEntryRequest_LogEntry) Reset()         { *m = AppendLogEntryRequest_LogEntry{} }
func (m *AppendLogEntryRequest_LogEntry) String() string { return proto.CompactTextString(m) }
func (*AppendLogEntryRequest_LogEntry) ProtoMessage()    {}

type AppendEntryResponse struct {
	Term    uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *AppendEntryResponse) Reset()         { *m = AppendEntryResponse{} }
func (m *AppendEntryResponse) String() string { return proto.CompactTextString(m) }
func (*AppendEntryResponse) ProtoMessage()    {}
