// Code generated by protoc-gen-go.
// source: request_vote.proto
// DO NOT EDIT!

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type VoteRequest struct {
	Term         uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	LastLogIndex uint32 `protobuf:"varint,2,opt,name=last_log_index" json:"last_log_index,omitempty"`
	LastLogTerm  uint32 `protobuf:"varint,3,opt,name=last_log_term" json:"last_log_term,omitempty"`
	CandidateId  string `protobuf:"bytes,4,opt,name=candidate_id" json:"candidate_id,omitempty"`
}

func (m *VoteRequest) Reset()         { *m = VoteRequest{} }
func (m *VoteRequest) String() string { return proto.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()    {}

type VoteResponse struct {
	Term        uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	VoteGranted bool   `protobuf:"varint,2,opt,name=vote_granted" json:"vote_granted,omitempty"`
}

func (m *VoteResponse) Reset()         { *m = VoteResponse{} }
func (m *VoteResponse) String() string { return proto.CompactTextString(m) }
func (*VoteResponse) ProtoMessage()    {}
