// Code generated by protoc-gen-go.
// source: rpc_service.proto
// DO NOT EDIT!

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for RpcService service

type RpcServiceClient interface {
	KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error)
	AppendLogEntries(ctx context.Context, in *AppendLogEntryRequest, opts ...grpc.CallOption) (*AppendEntryResponse, error)
	UpdateConfiguration(ctx context.Context, in *AppendConfigEntryRequest, opts ...grpc.CallOption) (*AppendEntryResponse, error)
	ElectLeader(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
	InstallSnapshot(ctx context.Context, in *InstallSnapshotRequest, opts ...grpc.CallOption) (*InstallSnapshotResponse, error)
}

type rpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewRpcServiceClient(cc *grpc.ClientConn) RpcServiceClient {
	return &rpcServiceClient{cc}
}

func (c *rpcServiceClient) KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error) {
	out := new(KeepAliveResponse)
	err := grpc.Invoke(ctx, "/rpc.RpcService/KeepAlive", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) AppendLogEntries(ctx context.Context, in *AppendLogEntryRequest, opts ...grpc.CallOption) (*AppendEntryResponse, error) {
	out := new(AppendEntryResponse)
	err := grpc.Invoke(ctx, "/rpc.RpcService/AppendLogEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) UpdateConfiguration(ctx context.Context, in *AppendConfigEntryRequest, opts ...grpc.CallOption) (*AppendEntryResponse, error) {
	out := new(AppendEntryResponse)
	err := grpc.Invoke(ctx, "/rpc.RpcService/UpdateConfiguration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) ElectLeader(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	out := new(VoteResponse)
	err := grpc.Invoke(ctx, "/rpc.RpcService/ElectLeader", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) InstallSnapshot(ctx context.Context, in *InstallSnapshotRequest, opts ...grpc.CallOption) (*InstallSnapshotResponse, error) {
	out := new(InstallSnapshotResponse)
	err := grpc.Invoke(ctx, "/rpc.RpcService/InstallSnapshot", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RpcService service

type RpcServiceServer interface {
	KeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveResponse, error)
	AppendLogEntries(context.Context, *AppendLogEntryRequest) (*AppendEntryResponse, error)
	UpdateConfiguration(context.Context, *AppendConfigEntryRequest) (*AppendEntryResponse, error)
	ElectLeader(context.Context, *VoteRequest) (*VoteResponse, error)
	InstallSnapshot(context.Context, *InstallSnapshotRequest) (*InstallSnapshotResponse, error)
}

func RegisterRpcServiceServer(s *grpc.Server, srv RpcServiceServer) {
	s.RegisterService(&_RpcService_serviceDesc, srv)
}

func _RpcService_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(KeepAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RpcServiceServer).KeepAlive(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _RpcService_AppendLogEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AppendLogEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RpcServiceServer).AppendLogEntries(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _RpcService_UpdateConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AppendConfigEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RpcServiceServer).UpdateConfiguration(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _RpcService_ElectLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RpcServiceServer).ElectLeader(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _RpcService_InstallSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(InstallSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RpcServiceServer).InstallSnapshot(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _RpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.RpcService",
	HandlerType: (*RpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KeepAlive",
			Handler:    _RpcService_KeepAlive_Handler,
		},
		{
			MethodName: "AppendLogEntries",
			Handler:    _RpcService_AppendLogEntries_Handler,
		},
		{
			MethodName: "UpdateConfiguration",
			Handler:    _RpcService_UpdateConfiguration_Handler,
		},
		{
			MethodName: "ElectLeader",
			Handler:    _RpcService_ElectLeader_Handler,
		},
		{
			MethodName: "InstallSnapshot",
			Handler:    _RpcService_InstallSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor1 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x41, 0x41, 0x70, 0x44, 0x6c, 0x47, 0x14, 0x89, 0xfa, 0x0a, 0x39, 0xd4, 0x9b, 0xb7,
	0x22, 0x05, 0xc5, 0xe0, 0xa1, 0x45, 0xaf, 0xb2, 0x26, 0x63, 0x5c, 0x88, 0x3b, 0xe3, 0xce, 0xb4,
	0xe0, 0xfb, 0xfa, 0x20, 0x96, 0x64, 0x5b, 0x62, 0xf0, 0xd0, 0xe3, 0x7e, 0xff, 0xff, 0x7f, 0xb0,
	0x03, 0xe3, 0x28, 0xe5, 0xab, 0x52, 0x5c, 0xf9, 0x92, 0x72, 0x89, 0x6c, 0x8c, 0xfb, 0x6b, 0x94,
	0x1d, 0x7f, 0x92, 0xaa, 0xab, 0x13, 0x9b, 0xfc, 0xec, 0x01, 0xcc, 0xa5, 0x5c, 0x74, 0x45, 0xbc,
	0x85, 0xc3, 0x47, 0x22, 0x99, 0x36, 0x7e, 0x45, 0x78, 0x96, 0xaf, 0x07, 0xf9, 0xf6, 0x3d, 0xa7,
	0xaf, 0x25, 0xa9, 0x65, 0xe7, 0x43, 0xac, 0xc2, 0x41, 0x09, 0xef, 0x61, 0x34, 0x15, 0xa1, 0x50,
	0x15, 0x5c, 0xcf, 0x82, 0x45, 0x4f, 0x8a, 0x59, 0xdb, 0xfd, 0x83, 0xbf, 0x37, 0x9e, 0x8b, 0x5e,
	0x96, 0x82, 0x64, 0x7a, 0x82, 0xd3, 0x67, 0xa9, 0x9c, 0xd1, 0x1d, 0x87, 0x77, 0x5f, 0x2f, 0xa3,
	0x33, 0xcf, 0x01, 0xaf, 0x7b, 0x83, 0x2e, 0xd9, 0xd1, 0x37, 0x81, 0xa3, 0x59, 0x43, 0xa5, 0x15,
	0xe4, 0x2a, 0x8a, 0x38, 0x6a, 0x8b, 0x2f, 0x6c, 0xdb, 0x2f, 0x8d, 0x7b, 0x24, 0x6d, 0x0a, 0x38,
	0x79, 0x08, 0x6a, 0xae, 0x69, 0x16, 0xc1, 0x89, 0x7e, 0xb0, 0xe1, 0x65, 0xdb, 0x1a, 0xd0, 0x8d,
	0xe2, 0xea, 0xff, 0xb0, 0xb3, 0xbd, 0x1d, 0xb4, 0xd7, 0xbe, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x4c, 0xe7, 0xf8, 0x08, 0x96, 0x01, 0x00, 0x00,
}
