// Code generated by protoc-gen-go.
// source: append_entries.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	append_entries.proto
	install_snapshot.proto
	request_vote.proto

It has these top-level messages:
	AppendEntriesRequest
	AppendEntriesResponse
	InstallSnapshotRequest
	InstallSnapshotResponse
	VoteRequest
	VoteResponse
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AppendEntriesRequest struct {
	Term          uint32                                `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	PrevLogIndex  uint32                                `protobuf:"varint,2,opt,name=prev_log_index" json:"prev_log_index,omitempty"`
	PrevLogTerm   uint32                                `protobuf:"varint,3,opt,name=prev_log_term" json:"prev_log_term,omitempty"`
	CommitIndex   uint32                                `protobuf:"varint,4,opt,name=commit_index" json:"commit_index,omitempty"`
	NodeLocations map[string]*AppendEntriesRequest_Node `protobuf:"bytes,5,rep,name=node_locations" json:"node_locations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Entries       []*AppendEntriesRequest_LogEntry      `protobuf:"bytes,6,rep,name=entries" json:"entries,omitempty"`
	LeaderId      string                                `protobuf:"bytes,7,opt,name=leader_id" json:"leader_id,omitempty"`
}

func (m *AppendEntriesRequest) Reset()         { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()    {}

func (m *AppendEntriesRequest) GetNodeLocations() map[string]*AppendEntriesRequest_Node {
	if m != nil {
		return m.NodeLocations
	}
	return nil
}

func (m *AppendEntriesRequest) GetEntries() []*AppendEntriesRequest_LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type AppendEntriesRequest_Node struct {
	Host string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *AppendEntriesRequest_Node) Reset()         { *m = AppendEntriesRequest_Node{} }
func (m *AppendEntriesRequest_Node) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRequest_Node) ProtoMessage()    {}

type AppendEntriesRequest_LogEntry struct {
	Cmd   string `protobuf:"bytes,1,opt,name=cmd" json:"cmd,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *AppendEntriesRequest_LogEntry) Reset()         { *m = AppendEntriesRequest_LogEntry{} }
func (m *AppendEntriesRequest_LogEntry) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRequest_LogEntry) ProtoMessage()    {}

type AppendEntriesResponse struct {
	Term    uint32 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *AppendEntriesResponse) Reset()         { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()    {}
